@ECHO off
title FoozBallKing Bot - Affection Module Terminal
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
node AffectionModule.js
pause